/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aeroivr_appserver_h323_OpenH323 */

#ifndef _Included_org_aeroivr_appserver_h323_OpenH323
#define _Included_org_aeroivr_appserver_h323_OpenH323
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aeroivr_appserver_h323_OpenH323
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_aeroivr_appserver_h323_OpenH323_init
  (JNIEnv *, jobject);

/*
 * Class:     org_aeroivr_appserver_h323_OpenH323
 * Method:    startListening
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_aeroivr_appserver_h323_OpenH323_startListening
  (JNIEnv *, jobject);

/*
 * Class:     org_aeroivr_appserver_h323_OpenH323
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_aeroivr_appserver_h323_OpenH323_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_aeroivr_appserver_h323_OpenH323
 * Method:    playAudioFileInChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aeroivr_appserver_h323_OpenH323_playAudioFileInChannel
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_aeroivr_appserver_h323_OpenH323
 * Method:    closeConnection
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_aeroivr_appserver_h323_OpenH323_closeConnection
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
